systemAPI:
  clientId: "781279af1525442fa93dd351ece0c99b"
  clientSecret: "414Af637020D428588e28Dacb0C8a057"

railwayReservation_SAPI:
  host: "railway-reservation-sapi.us-e2.cloudhub.io"
  
passengersPOI_SAPI:
  host: "passengers-poi-sapi.us-e2.cloudhub.io"
  storageBucket: "reservation-passengers-id-proofs"

trainDetails_SAPI:
  host: "train-details-sapi.us-e2.cloudhub.io"