systemAPI:
  clientId: "![Sz+riMeV0bg7eCMU2rbaBfKZcqCHuikFVFwbi3kgaOaUMHPpgxlHTuilF+GJD2OE]"
  clientSecret: "![BCytUz3ZaM1cnu6pfunvNcikul4D9krkX878csj8vIKHLBrBpCkyRKyhW6SZhjRN]"

railwayReservation_SAPI:
  host: "railway-reservation-sapi.us-e2.cloudhub.io"
  
passengersPOI_SAPI:
  host: "passengers-poi-sapi.us-e2.cloudhub.io"
  storageBucket: "reservation-passengers-id-proofs"

trainDetails_SAPI:
  host: "train-details-sapi.us-e2.cloudhub.io"